name: code style check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Black 23.1.0
        run: pip install black==23.1.0

      - name: Run Black to check code formatting
        run: black --check .
